### ISSUE TITLE
What's supposed to happen when I run gwion?

### ISSUE THREAD

**Issue by PaulBatchelor** [fennecdjay/Gwion#52]
With gwion compiled, I run this command:

    ./gwion examples/sine.gw

And nothing happens. Am I doing something wrong?

**Comment by fennecdjay** [comment]
No.
It is still my bad : confused:
I definitely need to write more about configure.
The most probable thing happening here is that you compiled with `dummy` as the default driver, so it runs, computes the sine, but does it as fast as possible and outputs no sound.
Looking at `util/config.template` (the file passed to `util/mk_configure.bash` in order to generate configure), it looks like `alsa` in on by default (so does `sndfile`).
so if you run
```sh
./gwion -d alsa examples/sine.gw
```

you should hear something, or at least it shoud attempt to play sound trough your default soundcard.

Very good issue title indeed.

**Comment by fennecdjay** [comment]
I'm gonna stop proscratinating and write `Configure.md` after a good sleep (it's almost 3 am in france at the time of writing 🕐 ).

**Comment by PaulBatchelor** [comment]
I can't use ALSA since I haven't configured the soundcard for it. Preferably, I'd like to use JACK.

Running ``./gwion -d sndfile example/sine.gw`` doesn't do anything either :/

**Comment by fennecdjay** [comment]
Good catch!
Jack should be working, but I haven't tested it since the build system update (I've only test alsa silent and dummy).
I'm gonna fix all that stuff, and warn you when it's done, hopefully before tomorrow evening.

I just can't tell you how grateful I am for your help.

**Comment by PaulBatchelor** [comment]
No problem. Keep up the good work!

Looking forward to your fixes.

**Comment by fennecdjay** [comment]
Things should be better now, yet I still have to write `Configure.md`. Warning you when it's done.

**Comment by fennecdjay** [comment]
As of `4c3d0a75`, there is now `Configure.md`, which should document the configure process.

**Comment by fennecdjay** [comment]
> Running ./gwion -d sndfile example/sine.gw doesn't do anything either :/

@PaulBatchelor, normally , if you run this, you should end up with `gwion_00.wav`  `gwion_01.wav` in your `/tmp` directory.  
You can change this location with the `-c` or `--card` flag:
```
./gwion -d sndfile -c my_file example/sine.gw
```
should create `my_file_00.wav` and `my_file_01.wav` in the current directory.  
I have to make it clearer somehow (it is already decribed in the help message, but it's a bit obscure)  
Sorry for the late answer.
