### ISSUE TITLE
Can't install on Fedora via instructions

### ISSUE THREAD

**Issue by royk** [fennecdjay/Gwion#66]
I installed soundpipe and followed the installation instructions, and got this:

alsa/asoundlib.h: no such file or directory.

Googling lead me here:
https://ubuntuforums.org/showthread.php?t=1586707

Solved by running:
sudo yum install alsa-lib-devel

**Comment by fennecdjay** [comment]
Thank you @royk for your interrest.
I use [Archlinux](https://www.archlinux.org/), on which devellopment headers are always installed with the library, that's why I didn't figured out I should mention installing them on the instructions.
Please keep this opened until instructions are fixed.
And let me know if you run into more problems 😕 .

**Comment by fennecdjay** [comment]
> Don't forget you'll need the header for your driver (e.g. xxx-dev on debian-like distro)

@royk do you think that would do (when placed in the Driver section)?

**Comment by fennecdjay** [comment]
Issue look dead.
